### ISSUE TITLE
version 0.4 fails to install

### ISSUE THREAD

**Issue by onlinespending** [fallenhitokiri/autocomplete-plus-jedi#2]
Installing “autocomplete-plus-jedi@0.0.4” failed.Hide output…

> execsyncs@0.1.1 install /private/var/folders/c0/t0f9l0l90cs14f692yvq2nvr0000gn/T/apm-install-dir-11515-4983-10azbyz/node_modules/autocomplete-plus-jedi/node_modules/execsyncs
> node-gyp rebuild

  CXX(target) Release/obj.target/shell/execsync.o

In file included from ../execsync.cc:4:
../node_modules/nan/nan.h:67:21: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
typedef v8::String::ExternalAsciiStringResource
        ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                    ExternalStringResource
/Users/Ben/.atom/.node-gyp/.node-gyp/0.21.0/deps/v8/include/v8.h:1936:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../execsync.cc:4:
In file included from ../node_modules/nan/nan.h:74:
../node_modules/nan/nan_new.h:164:26: error: class member cannot be redeclared
  static inline return_t New(NanExternalOneByteStringResource \* value);
                         ^
../node_modules/nan/nan_new.h:163:26: note: previous declaration is here
  static inline return_t New(v8::String::ExternalStringResource \* value);
                         ^
In file included from ../execsync.cc:4:
In file included from ../node_modules/nan/nan.h:74:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:222:22: error: redefinition of 'New'
Factoryv8::String::New(NanExternalOneByteStringResource \* value) {
                     ^
../node_modules/nan/nan_implementation_12_inl.h:217:22: note: previous definition is here
Factoryv8::String::New(v8::String::ExternalStringResource \* value) {
                     ^
In file included from ../execsync.cc:4:
In file included from ../node_modules/nan/nan.h:74:
../node_modules/nan/nan_new.h:319:1: error: redefinition of 'NanNew'
NanNew(NanExternalOneByteStringResource \* value) {
^
../node_modules/nan/nan_new.h:313:1: note: previous definition is here
NanNew(v8::String::ExternalStringResource \* value) {
^
In file included from ../execsync.cc:4:
../node_modules/nan/nan.h:1790:17: error: no member named 'GetExternalAsciiStringResource' in 'v8::String'; did you mean 'GetExternalOneByteStringResource'?
    return str->GetExternalAsciiStringResource();
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                GetExternalOneByteStringResource
/Users/Ben/.atom/.node-gyp/.node-gyp/0.21.0/deps/v8/include/v8.h:2003:40: note: 'GetExternalOneByteStringResource' declared here
  const ExternalOneByteStringResource\* GetExternalOneByteStringResource() const;
                                       ^
In file included from ../execsync.cc:4:
../node_modules/nan/nan.h:1790:12: error: cannot initialize return object of type 'const NanExternalOneByteStringResource _' (aka 'const v8::String::ExternalStringResource *') with an rvalue of type 'const v8::String::ExternalOneByteStringResource *'
    return str->GetExternalAsciiStringResource();
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1800:17: error: no member named 'IsExternalAscii' in 'v8::String'; did you mean 'IsExternal'?
    return str->IsExternalAscii();
                ^~~~~~~~~~~~~~~
                IsExternal
/Users/Ben/.atom/.node-gyp/.node-gyp/0.21.0/deps/v8/include/v8.h:1900:8: note: 'IsExternal' declared here
  bool IsExternal() const;
       ^
In file included from ../execsync.cc:4:
../node_modules/nan/nan.h:1825:11: error: assigning to 'const char *' from incompatible type 'const uint16_t *' (aka 'const unsigned short *')
    *data = ext->data();
          ^ ~~~~~~~~~~~
../node_modules/nan/nan.h:1848:10: error: no matching function for call to 'Encode'
  return node::Encode(
         ^~~~~~~~~~~~
/Users/Ben/.atom/.node-gyp/.node-gyp/0.21.0/src/node.h:272:34: note: candidate function not viable: cannot convert argument of incomplete type 'const void *' to 'const char *'
NODE_EXTERN v8::Localv8::Value Encode(v8::Isolate_ isolate,
                                 ^
/Users/Ben/.atom/.node-gyp/.node-gyp/0.21.0/src/node.h:278:34: note: candidate function not viable: requires 3 arguments, but 4 were provided
NODE_EXTERN v8::Localv8::Value Encode(v8::Isolate\* isolate,
                                 ^
/Users/Ben/.atom/.node-gyp/.node-gyp/0.21.0/src/node.h:283:45: note: candidate function not viable: requires at most 3 arguments, but 4 were provided
                inline v8::Localv8::Value Encode(
                                            ^
/Users/Ben/.atom/.node-gyp/.node-gyp/0.21.0/src/node.h:64:53: note: expanded from macro 'NODE_DEPRECATED'
# define NODE_DEPRECATED(msg, fn) V8_DEPRECATED(msg, fn)

```
                                                ^
```

/Users/Ben/.atom/.node-gyp/.node-gyp/0.21.0/deps/v8/include/v8config.h:329:45: note: expanded from macro 'V8_DEPRECATED'
# define V8_DEPRECATED(message, declarator) declarator

```
                                        ^
```

9 errors generated.
make: **\* [Release/obj.target/shell/execsync.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/c0/t0f9l0l90cs14f692yvq2nvr0000gn/T/apm-install-dir-11515-4983-10azbyz/node_modules/autocomplete-plus-jedi/node_modules/execsyncs
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.1.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Applications/Atom.app/Contents/Resources/app/apm/.apmrc" "--userconfig" "/Users/Ben/.atom/.apmrc" "install" "/private/var/folders/c0/t0f9l0l90cs14f692yvq2nvr0000gn/T/d-11515-4983-16bsm5k/package.tgz" "--target=0.21.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE

npm ERR! execsyncs@0.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the execsyncs@0.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the execsyncs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls execsyncs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/c0/t0f9l0l90cs14f692yvq2nvr0000gn/T/apm-install-dir-11515-4983-10azbyz/npm-debug.log

**Comment by fallenhitokiri** [comment]
Thanks for the log.

The next release will likely drop execsync and move to the new async API autocomplete plus provides.

**Comment by samirotiv** [comment]
Experiencing the same issue.

Very eager to use Jedi autocompletions!.

**Comment by ielezovikj** [comment]
I have the same problem as well.

**Comment by Finkes** [comment]
Same issue here. Can't install.

**Comment by fallenhitokiri** [comment]
I am aware of the problem, but won't be able to fix it before next weekend. It requires quite a bit work to get it to play nicely with ACP again.

**Comment by fallenhitokiri** [comment]
I just pushed a new version that doesn't require 3rd party dependencies anymore but uses autocomplete-plus's async API. This should resolve this issue.

I'm keeping this issue open until someone confirms that the error is fixed.

**Comment by justyns** [comment]
I can confirm that I am no longer getting the error mentioned in this issue.   Atom was able to successfully update autocomplete-plus-jedi to 0.0.7.

I haven't tested it much yet, but so far seems to be working :)

**Comment by fallenhitokiri** [comment]
Thanks
